#!/bin/bash

display_output () {
  echo "---"
  printf "$1\n"
  echo "---"
  echo ""
}

if [ "$EUID" -ne 0 ]; then
  display_output "Please run as root.\nExiting."
  exit 1
fi

if ! $(systemctl list-units --full -all | grep -Fq "terraria.service"); then
  display_output "Service 'terraria' does not exist.\nExiting."
  exit 1
fi

server_url=$1
server_config_url='https://raw.githubusercontent.com/baoist/terraria-server/master/resources/serverconfig.txt'

if [[ ! -n "$server_url" ]]; then
  display_output "Server URL argument not passed.\nExiting"
  exit 1
fi

tmp_dir=/tmp/upgrade-terraria

mkdir -p $tmp_dir
cd $tmp_dir

display_output "Downloading file from passed argument '${server_url}'."
curl -s -O $server_url

if [[ $? != 0 ]]; then
  display_output "Unable to download zip.\nExiting"
  exit 1
fi

zip_name=${server_url##*/}
src_dir=/opt/
srv_dir=/srv/
tmp_name="terraria.server.tmp"

rm -rf "${tmp_name}.zip" $tmp_name
mv ${zip_name} "${tmp_name}.zip"

unzip -o "${tmp_name}.zip" -d $tmp_name > /dev/null

versioned_dir_name=$(ls -d terraria.server.tmp/* | tr ' ' '\n' | tail -n 1)

if [[ "systemctl is-active --quiet terraria" ]]; then
  display_output "Stopping Terraria server."
  sudo systemctl stop terraria
else
  display_output "Terraria server currently not running."
fi

{
  cd $src_dir
  if [ -d "./terraria.bkp" ]; then
    rm -rf ./terraria.bkp.1
    mv ./terraria.bkp ./terraria.bkp.1
  fi

  if [ -d "./terraria" ]; then
    mv ./terraria ./terraria.bkp
  fi

  if [ ! -d "${tmp_dir}/${versioned_dir_name}/Linux" ]; then
    display_output "Unable to find temporary directory '${tmp_dir}/${versioned_dir_name}/Linux' (possibly 'Linux' was renamed?).\nRestoring and exiting"
    exit 1
  fi

  mv "${tmp_dir}/${versioned_dir_name}/Linux/" ./terraria
  cd ./terraria

  display_output "Downloading 'serverconfig.txt' from source '${server_config_url}'."
  curl -s -O $server_config_url

  sudo chmod +x TerrariaServer.bin.x86_64

  if [ -d "./terraria.bkp.1" ]; then
    rm -rf ./terraria.bkp.1
  fi
} || {
  display_output "Failed to move new server, reverting to previous version"

  cd $src_dir

  if [ -d "./terraria.bkp" ]; then
    rm -rf ./terraria
    mv ./terraria.bkp ./terraria
  fi

  if [ -d "./terraria.bkp.1" ]; then
    mv ./terraria.bkp.1 ./terraria.bkp
  fi
}

version_in_dir=$(head -n 1 changelog.txt| grep -Po '(([0-9]{1,2}(\.)?)+)')
display_output "Version set to: ${version_in_dir}"

display_output "Starting Terraria server"
sudo systemctl start terraria

sudo systemctl status terraria
